/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoperachaFactory,
  ICoperachaFactoryInterface,
} from "../../CoperachaWallet.sol/ICoperachaFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_member",
        type: "address",
      },
    ],
    name: "registerMemberToVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoperachaFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ICoperachaFactoryInterface {
    return new Interface(_abi) as ICoperachaFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICoperachaFactory {
    return new Contract(address, _abi, runner) as unknown as ICoperachaFactory;
  }
}
