/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoperachaWallet__factory } from "./CoperachaWallet__factory";
export { ICoperachaFactory__factory } from "./ICoperachaFactory__factory";
