/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as coperachaWalletSol from "./CoperachaWallet.sol";
export { CoperachaFactory__factory } from "./CoperachaFactory__factory";
