/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoperachaFactory__factory } from "./CoperachaFactory__factory";
export { CoperachaWallet__factory } from "./CoperachaWallet__factory";
