/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoperachaWallet } from "./CoperachaWallet";
export type { ICoperachaFactory } from "./ICoperachaFactory";
