/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CoperachaFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allVaults"
      | "createVault"
      | "getAllVaults"
      | "getTotalVaults"
      | "getUserVaultCount"
      | "getUserVaults"
      | "getVaultInfo"
      | "getVaultsByRange"
      | "isValidVault"
      | "isVault"
      | "registerMemberToVault"
      | "userVaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MemberAddedToVault" | "VaultCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [string, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaultCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMemberToVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVaults",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaultCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMemberToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userVaults", data: BytesLike): Result;
}

export namespace MemberAddedToVaultEvent {
  export type InputTuple = [vaultAddress: AddressLike, member: AddressLike];
  export type OutputTuple = [vaultAddress: string, member: string];
  export interface OutputObject {
    vaultAddress: string;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultAddress: AddressLike,
    name: string,
    members: AddressLike[],
    creator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultAddress: string,
    name: string,
    members: string[],
    creator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultAddress: string;
    name: string;
    members: string[];
    creator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoperachaFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CoperachaFactory;
  waitForDeployment(): Promise<this>;

  interface: CoperachaFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createVault: TypedContractMethod<
    [_name: string, _members: AddressLike[]],
    [string],
    "nonpayable"
  >;

  getAllVaults: TypedContractMethod<[], [string[]], "view">;

  getTotalVaults: TypedContractMethod<[], [bigint], "view">;

  getUserVaultCount: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getUserVaults: TypedContractMethod<[_user: AddressLike], [string[]], "view">;

  getVaultInfo: TypedContractMethod<
    [_vaultAddress: AddressLike],
    [
      [string, string[], bigint, bigint] & {
        name: string;
        members: string[];
        balance: bigint;
        proposalCounter: bigint;
      }
    ],
    "view"
  >;

  getVaultsByRange: TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;

  isValidVault: TypedContractMethod<[_vault: AddressLike], [boolean], "view">;

  isVault: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  registerMemberToVault: TypedContractMethod<
    [_member: AddressLike],
    [void],
    "nonpayable"
  >;

  userVaults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [_name: string, _members: AddressLike[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVaultCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVaults"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultInfo"
  ): TypedContractMethod<
    [_vaultAddress: AddressLike],
    [
      [string, string[], bigint, bigint] & {
        name: string;
        members: string[];
        balance: bigint;
        proposalCounter: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultsByRange"
  ): TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidVault"
  ): TypedContractMethod<[_vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVault"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerMemberToVault"
  ): TypedContractMethod<[_member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userVaults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "MemberAddedToVault"
  ): TypedContractEvent<
    MemberAddedToVaultEvent.InputTuple,
    MemberAddedToVaultEvent.OutputTuple,
    MemberAddedToVaultEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "MemberAddedToVault(address,address)": TypedContractEvent<
      MemberAddedToVaultEvent.InputTuple,
      MemberAddedToVaultEvent.OutputTuple,
      MemberAddedToVaultEvent.OutputObject
    >;
    MemberAddedToVault: TypedContractEvent<
      MemberAddedToVaultEvent.InputTuple,
      MemberAddedToVaultEvent.OutputTuple,
      MemberAddedToVaultEvent.OutputObject
    >;

    "VaultCreated(address,string,address[],address,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
