/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coperachaWalletSol from "./CoperachaWallet.sol";
export type { coperachaWalletSol };
export type { CoperachaFactory } from "./CoperachaFactory";
export * as factories from "./factories";
export { CoperachaFactory__factory } from "./factories/CoperachaFactory__factory";
export type { CoperachaWallet } from "./CoperachaWallet.sol/CoperachaWallet";
export { CoperachaWallet__factory } from "./factories/CoperachaWallet.sol/CoperachaWallet__factory";
export type { ICoperachaFactory } from "./CoperachaWallet.sol/ICoperachaFactory";
export { ICoperachaFactory__factory } from "./factories/CoperachaWallet.sol/ICoperachaFactory__factory";
