/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoperachaFactory } from "./CoperachaFactory";
export type { CoperachaWallet } from "./CoperachaWallet";
export * as factories from "./factories";
export { CoperachaFactory__factory } from "./factories/CoperachaFactory__factory";
export { CoperachaWallet__factory } from "./factories/CoperachaWallet__factory";
